spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: #your database url
    username: #your database username
    password: #your database password
    hikari:
      auto-commit: false
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.yaml
  mail:
    host: smtp.gmail.com
    port: 587
    username: todolistorganization@gmail.com
    password: rgankytzymfbyphy
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

mybatis:
  config-location: classpath:db/mybatis/mybatis-config.xml
  mapper-locations: classpath:db/mybatis/mapper/*.xml
  type-aliases-package: com.project.etaskify.model.entity

server:
  port: 5000

